package goanalysis

import (
	"testing"

	"github.com/gdevillele/vet/implementations/go/internal/config"
)

func TestAnalyzeFileReportsFunctionsWithTooManyParameters(t *testing.T) {
	source := []byte(`package sample

func accepted(value int) {}

func rejected(left int, right int) {}

var _ = func(first string, second string) {}
`)

	diagnostics, err := New(config.Default()).AnalyzeFile(AnalyzeFileRequest{
		Path:   "sample.go",
		Source: source,
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}

	if len(diagnostics) != 2 {
		t.Fatalf("expected 2 diagnostics, got %d: %#v", len(diagnostics), diagnostics)
	}

	if diagnostics[0].RuleID != RuleMaxFunctionParameters {
		t.Fatalf("expected first diagnostic rule %q, got %q", RuleMaxFunctionParameters, diagnostics[0].RuleID)
	}

	if diagnostics[0].Line != 5 {
		t.Fatalf("expected rejected function on line 5, got line %d", diagnostics[0].Line)
	}

	if diagnostics[1].Line != 7 {
		t.Fatalf("expected function literal on line 7, got line %d", diagnostics[1].Line)
	}
}

func TestAnalyzeFileCountsGroupedParameterNames(t *testing.T) {
	source := []byte(`package sample

func rejected(left, right int) {}
`)

	diagnostics, err := New(config.Default()).AnalyzeFile(AnalyzeFileRequest{
		Path:   "sample.go",
		Source: source,
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}
}

func TestAnalyzeFileReportsMissingRequiredHeader(t *testing.T) {
	cfg := config.Default()
	cfg.SourceFileHeader.Required = true

	diagnostics, err := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path:   "sample.go",
		Source: []byte("package sample\n"),
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}

	if diagnostics[0].RuleID != RuleSourceFileHeaderRequired {
		t.Fatalf("expected rule %q, got %q", RuleSourceFileHeaderRequired, diagnostics[0].RuleID)
	}
}

func TestAnalyzeFileReportsHeaderBelowMinimumLength(t *testing.T) {
	cfg := config.Default()
	cfg.SourceFileHeader.MinLength = 5

	diagnostics, err := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path: "sample.go",
		Source: []byte(`// Tiny
package sample
`),
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}

	if diagnostics[0].RuleID != RuleSourceFileHeaderMin {
		t.Fatalf("expected rule %q, got %q", RuleSourceFileHeaderMin, diagnostics[0].RuleID)
	}
}

func TestAnalyzeFileReportsHeaderAboveMaximumLength(t *testing.T) {
	cfg := config.Default()
	cfg.SourceFileHeader.MaxLength = 5

	diagnostics, err := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path: "sample.go",
		Source: []byte(`// Too long
package sample
`),
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}

	if diagnostics[0].RuleID != RuleSourceFileHeaderMax {
		t.Fatalf("expected rule %q, got %q", RuleSourceFileHeaderMax, diagnostics[0].RuleID)
	}
}

func TestAnalyzeFileSkipsBuildTagsWhenFindingHeader(t *testing.T) {
	cfg := config.Default()
	cfg.SourceFileHeader.Required = true
	cfg.SourceFileHeader.MinLength = 10

	diagnostics, err := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path: "sample.go",
		Source: []byte(`//go:build linux

// Project header
package sample
`),
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}

	if len(diagnostics) != 0 {
		t.Fatalf("expected no diagnostics, got %d: %#v", len(diagnostics), diagnostics)
	}
}

func TestAnalyzeFileDoesNotUseGeneratedMarkerAsHeader(t *testing.T) {
	cfg := config.Default()
	cfg.SourceFileHeader.Required = true

	diagnostics, err := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path: "sample.go",
		Source: []byte(`// Code generated by test; DO NOT EDIT.
package sample
`),
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}

	if diagnostics[0].RuleID != RuleSourceFileHeaderRequired {
		t.Fatalf("expected rule %q, got %q", RuleSourceFileHeaderRequired, diagnostics[0].RuleID)
	}
}

func TestAnalyzeFileReportsSourceFileAboveMaximumLines(t *testing.T) {
	cfg := config.Default()
	cfg.SourceFileLines.Max = 2

	diagnostics, err := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path: "sample.go",
		Source: []byte(`package sample

var value = 1
`),
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}

	if diagnostics[0].RuleID != RuleSourceFileLines {
		t.Fatalf("expected rule %q, got %q", RuleSourceFileLines, diagnostics[0].RuleID)
	}
}

func TestAnalyzeFileReportsFunctionBodyAboveMaximumLines(t *testing.T) {
	cfg := config.Default()
	cfg.FunctionBodyLines.Max = 1

	diagnostics, err := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path: "sample.go",
		Source: []byte(`package sample

func rejected() {
	println("one")
	println("two")
}
`),
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}

	if diagnostics[0].RuleID != RuleFunctionBodyLines {
		t.Fatalf("expected rule %q, got %q", RuleFunctionBodyLines, diagnostics[0].RuleID)
	}
}

func TestAnalyzeFileReportsMissingMandatoryFunctionDocstring(t *testing.T) {
	cfg := config.Default()
	cfg.FunctionDocstring.Policy = config.FunctionDocstringMandatory

	diagnostics, err := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path: "sample.go",
		Source: []byte(`package sample

func missing() {}

// documented has a docstring.
func documented() {}
`),
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}

	if diagnostics[0].RuleID != RuleFunctionDocstring {
		t.Fatalf("expected rule %q, got %q", RuleFunctionDocstring, diagnostics[0].RuleID)
	}
}

func TestAnalyzeFileReportsForbiddenFunctionDocstring(t *testing.T) {
	cfg := config.Default()
	cfg.FunctionDocstring.Policy = config.FunctionDocstringForbidden

	diagnostics, err := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path: "sample.go",
		Source: []byte(`package sample

// documented has a docstring.
func documented() {}
`),
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}

	if diagnostics[0].RuleID != RuleFunctionDocstring {
		t.Fatalf("expected rule %q, got %q", RuleFunctionDocstring, diagnostics[0].RuleID)
	}
}

func TestAnalyzeFileReportsTabsWhenSpacesIndentRequired(t *testing.T) {
	cfg := config.Default()
	cfg.Indent.Type = config.IndentSpaces

	diagnostics, err := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path:   "sample.go",
		Source: []byte("package sample\n\nfunc rejected() {\n\tprintln(\"one\")\n}\n"),
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}

	if diagnostics[0].RuleID != RuleIndentType {
		t.Fatalf("expected rule %q, got %q", RuleIndentType, diagnostics[0].RuleID)
	}
}

func TestAnalyzeFileReportsSpacesWhenTabsIndentRequired(t *testing.T) {
	cfg := config.Default()
	cfg.Indent.Type = config.IndentTabs

	diagnostics, err := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path:   "sample.go",
		Source: []byte("package sample\n\nfunc rejected() {\n  println(\"one\")\n}\n"),
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}

	if diagnostics[0].RuleID != RuleIndentType {
		t.Fatalf("expected rule %q, got %q", RuleIndentType, diagnostics[0].RuleID)
	}
}

func TestAnalyzeFileReportsIndentWidthViolation(t *testing.T) {
	cfg := config.Default()
	cfg.Indent.Type = config.IndentSpaces
	cfg.Indent.Width = 4

	diagnostics, err := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path:   "sample.go",
		Source: []byte("package sample\n\nfunc rejected() {\n  println(\"one\")\n}\n"),
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}

	if diagnostics[0].RuleID != RuleIndentWidth {
		t.Fatalf("expected rule %q, got %q", RuleIndentWidth, diagnostics[0].RuleID)
	}
}

func TestAnalyzeFileIgnoresRawStringIndentation(t *testing.T) {
	diagnostics, err := New(config.Default()).AnalyzeFile(AnalyzeFileRequest{
		Path:   "sample.go",
		Source: []byte("package sample\n\nvar text = `\n  not Go indentation\n`\n"),
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}

	if len(diagnostics) != 0 {
		t.Fatalf("expected no diagnostics, got %d: %#v", len(diagnostics), diagnostics)
	}
}

func TestAnalyzeFileReportsCasingDiagnostics(t *testing.T) {
	cfg := config.Default()
	cfg.Casing.Enabled = true
	cfg.Casing.Functions = config.CasingCamelCase
	cfg.Casing.Variables = config.CasingCamelCase
	cfg.Casing.Types = config.CasingUpperCamelCase
	cfg.Casing.Constants = config.CasingSnakeUpperCase

	diagnostics, err := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path: "sample.go",
		Source: []byte(`package sample

const max_connections = 1

type user_record struct{}

var global_value = 1

func accepted(bad_param int) {
	Bad_local := bad_param
}

func Rejected() {}
`),
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}

	seen := map[string]bool{}
	for _, item := range diagnostics {
		seen[item.RuleID] = true
	}

	for _, rule := range []string{RuleConstantCasing, RuleTypeCasing, RuleVariableCasing, RuleFunctionCasing} {
		if !seen[rule] {
			t.Fatalf("expected %s diagnostic in %#v", rule, diagnostics)
		}
	}
}

func TestAnalyzeFileAcceptsGoLanguageDefaultCasing(t *testing.T) {
	cfg := config.Default()
	cfg.Casing.Enabled = true

	diagnostics, err := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path: "sample.go",
		Source: []byte(`package sample

const MaxConnections = 1
const maxConnections = 2

type UserRecord struct{}
type userRecord struct{}

var RequestID = 1
var requestID = 2

func ServeHTTP() {}
func serveHTTP() {}
`),
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}

	if len(diagnostics) != 0 {
		t.Fatalf("expected no diagnostics, got %d: %#v", len(diagnostics), diagnostics)
	}
}

func TestAnalyzeFileHonorsCasingIgnores(t *testing.T) {
	cfg := config.Default()
	cfg.Casing.Enabled = true
	cfg.Casing.Functions = config.CasingCamelCase
	cfg.Casing.IgnorePatterns = []string{"^Test[A-Z]"}

	diagnostics, err := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path: "sample.go",
		Source: []byte(`package sample

func TestAccepted() {}
`),
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}

	if len(diagnostics) != 0 {
		t.Fatalf("expected no diagnostics, got %d: %#v", len(diagnostics), diagnostics)
	}
}

func TestAnalyzeWorkflowFileReportsUnpinnedGitHubActions(t *testing.T) {
	cfg := config.Default()
	cfg.GithubActionsPinned.Enabled = true

	tests := []struct {
		name   string
		action string
	}{
		{name: "tag", action: "actions/checkout@v5"},
		{name: "branch", action: "actions/checkout@main"},
		{name: "missing-ref", action: "actions/checkout"},
		{name: "short-sha", action: "actions/checkout@f43a0e5ff2bd"},
		{name: "non-hex-40", action: "actions/checkout@zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			diagnostics, err := New(cfg).AnalyzeWorkflowFile(AnalyzeWorkflowFileRequest{
				Path: "workflow.yml",
				Source: []byte(`name: test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ` + test.action + `
`),
			})
			if err != nil {
				t.Fatalf("AnalyzeWorkflowFile returned error: %v", err)
			}
			if len(diagnostics) != 1 {
				t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
			}
			if diagnostics[0].RuleID != RuleGithubActionsPinned {
				t.Fatalf("expected rule %q, got %q", RuleGithubActionsPinned, diagnostics[0].RuleID)
			}
			if diagnostics[0].Line != 6 {
				t.Fatalf("expected diagnostic on line 6, got %d", diagnostics[0].Line)
			}
		})
	}
}

func TestAnalyzeWorkflowFileAcceptsPinnedAndIgnoredGitHubActions(t *testing.T) {
	cfg := config.Default()
	cfg.GithubActionsPinned.Enabled = true

	tests := []struct {
		name   string
		source string
	}{
		{
			name: "full-sha",
			source: `name: test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
`,
		},
		{
			name: "full-sha-uppercase",
			source: `name: test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@F43A0E5FF2BD294095638E18286CA9A3D1956744
`,
		},
		{
			name: "nested-action-path",
			source: `name: test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: owner/repo/path/to/action@f43a0e5ff2bd294095638e18286ca9a3d1956744
`,
		},
		{
			name: "local-action",
			source: `name: test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build
`,
		},
		{
			name: "docker-action",
			source: `name: test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://alpine:3.19
`,
		},
		{
			name: "reusable-workflow",
			source: `name: test
jobs:
  call:
    uses: owner/repo/.github/workflows/build.yml@main
`,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			diagnostics, err := New(cfg).AnalyzeWorkflowFile(AnalyzeWorkflowFileRequest{
				Path:   "workflow.yml",
				Source: []byte(test.source),
			})
			if err != nil {
				t.Fatalf("AnalyzeWorkflowFile returned error: %v", err)
			}
			if len(diagnostics) != 0 {
				t.Fatalf("expected no diagnostics, got %d: %#v", len(diagnostics), diagnostics)
			}
		})
	}
}
