mod common;

use vet::{
    analysis::{
        RULE_CONSTANT_CASING, RULE_FUNCTION_BODY_LINES, RULE_FUNCTION_CASING,
        RULE_FUNCTION_DOCSTRING, RULE_GITHUB_ACTIONS_PINNED, RULE_INDENT_TYPE, RULE_INDENT_WIDTH,
        RULE_MAX_FUNCTION_PARAMETERS, RULE_SOURCE_FILE_HEADER_MAX, RULE_SOURCE_FILE_HEADER_MIN,
        RULE_SOURCE_FILE_HEADER_REQUIRED, RULE_SOURCE_FILE_LINES, RULE_TYPE_CASING,
        RULE_VARIABLE_CASING,
    },
    config::{CasingStyle, Config, FunctionDocstringPolicy, IndentType},
};

use common::{analyze, analyze_workflow};

#[test]
fn reports_functions_with_too_many_parameters() {
    let source = r#"
fn accepted(value: i32) {}

fn rejected(left: i32, right: i32) {}
"#;

    let diagnostics = analyze(Config::default(), source);

    assert_eq!(diagnostics.len(), 1, "{diagnostics:#?}");
    assert_eq!(diagnostics[0].rule_id, RULE_MAX_FUNCTION_PARAMETERS);
    assert_eq!(diagnostics[0].line, 4);
    assert_eq!(diagnostics[0].column, 4);
}

#[test]
fn does_not_count_method_receiver_as_parameter() {
    let source = r#"
struct Sample;

impl Sample {
    fn accepted(&self, value: i32) {}
}
"#;

    let diagnostics = analyze(Config::default(), source);

    assert!(diagnostics.is_empty(), "{diagnostics:#?}");
}

#[test]
fn reports_missing_required_header() {
    let mut config = Config::default();
    config.source_file_header.required = true;

    let diagnostics = analyze(config, "fn missing() {}\n");

    assert_eq!(diagnostics.len(), 1, "{diagnostics:#?}");
    assert_eq!(diagnostics[0].rule_id, RULE_SOURCE_FILE_HEADER_REQUIRED);
}

#[test]
fn reports_header_below_minimum_length() {
    let mut config = Config::default();
    config.source_file_header.min_length = 5;

    let diagnostics = analyze(config, "// Tiny\nfn accepted() {}\n");

    assert_eq!(diagnostics.len(), 1, "{diagnostics:#?}");
    assert_eq!(diagnostics[0].rule_id, RULE_SOURCE_FILE_HEADER_MIN);
}

#[test]
fn reports_header_above_maximum_length() {
    let mut config = Config::default();
    config.source_file_header.max_length = 5;

    let diagnostics = analyze(config, "// Too long\nfn accepted() {}\n");

    assert_eq!(diagnostics.len(), 1, "{diagnostics:#?}");
    assert_eq!(diagnostics[0].rule_id, RULE_SOURCE_FILE_HEADER_MAX);
}

#[test]
fn skips_shebang_when_finding_header() {
    let mut config = Config::default();
    config.source_file_header.required = true;
    config.source_file_header.min_length = 10;

    let diagnostics = analyze(
        config,
        r#"#!/usr/bin/env rust-script

// Project header
fn accepted() {}
"#,
    );

    assert!(diagnostics.is_empty(), "{diagnostics:#?}");
}

#[test]
fn does_not_use_generated_marker_as_header() {
    let mut config = Config::default();
    config.source_file_header.required = true;

    let diagnostics = analyze(
        config,
        r#"// Code generated by test; DO NOT EDIT.
fn accepted() {}
"#,
    );

    assert_eq!(diagnostics.len(), 1, "{diagnostics:#?}");
    assert_eq!(diagnostics[0].rule_id, RULE_SOURCE_FILE_HEADER_REQUIRED);
}

#[test]
fn reports_source_file_above_maximum_lines() {
    let mut config = Config::default();
    config.source_file_lines.max = 2;

    let diagnostics = analyze(
        config,
        r#"const ONE: i32 = 1;
const TWO: i32 = 2;
const THREE: i32 = 3;
"#,
    );

    assert_eq!(diagnostics.len(), 1, "{diagnostics:#?}");
    assert_eq!(diagnostics[0].rule_id, RULE_SOURCE_FILE_LINES);
}

#[test]
fn reports_function_body_above_maximum_lines() {
    let mut config = Config::default();
    config.function_body_lines.max = 1;

    let diagnostics = analyze(
        config,
        r#"fn rejected() {
    println!("one");
    println!("two");
}
"#,
    );

    assert_eq!(diagnostics.len(), 1, "{diagnostics:#?}");
    assert_eq!(diagnostics[0].rule_id, RULE_FUNCTION_BODY_LINES);
}

#[test]
fn reports_missing_mandatory_function_docstring() {
    let mut config = Config::default();
    config.function_docstring.policy = FunctionDocstringPolicy::Mandatory;

    let diagnostics = analyze(
        config,
        r#"fn missing() {}

/// documented has a docstring.
fn documented() {}
"#,
    );

    assert_eq!(diagnostics.len(), 1, "{diagnostics:#?}");
    assert_eq!(diagnostics[0].rule_id, RULE_FUNCTION_DOCSTRING);
}

#[test]
fn reports_forbidden_function_docstring() {
    let mut config = Config::default();
    config.function_docstring.policy = FunctionDocstringPolicy::Forbidden;

    let diagnostics = analyze(
        config,
        r#"/// documented has a docstring.
fn documented() {}
"#,
    );

    assert_eq!(diagnostics.len(), 1, "{diagnostics:#?}");
    assert_eq!(diagnostics[0].rule_id, RULE_FUNCTION_DOCSTRING);
}

#[test]
fn reports_tabs_when_spaces_indent_required() {
    let mut config = Config::default();
    config.indent.r#type = IndentType::Spaces;

    let diagnostics = analyze(config, "fn rejected() {\n\tprintln!(\"one\");\n}\n");

    assert_eq!(diagnostics.len(), 1, "{diagnostics:#?}");
    assert_eq!(diagnostics[0].rule_id, RULE_INDENT_TYPE);
}

#[test]
fn reports_spaces_when_tabs_indent_required() {
    let mut config = Config::default();
    config.indent.r#type = IndentType::Tabs;

    let diagnostics = analyze(config, "fn rejected() {\n  println!(\"one\");\n}\n");

    assert_eq!(diagnostics.len(), 1, "{diagnostics:#?}");
    assert_eq!(diagnostics[0].rule_id, RULE_INDENT_TYPE);
}

#[test]
fn reports_indent_width_violation() {
    let mut config = Config::default();
    config.indent.r#type = IndentType::Spaces;
    config.indent.width = 4;

    let diagnostics = analyze(config, "fn rejected() {\n  println!(\"one\");\n}\n");

    assert_eq!(diagnostics.len(), 1, "{diagnostics:#?}");
    assert_eq!(diagnostics[0].rule_id, RULE_INDENT_WIDTH);
}

#[test]
fn uses_rust_language_default_indentation() {
    let diagnostics = analyze(
        Config::default(),
        "fn rejected() {\n\tprintln!(\"one\");\n}\n",
    );

    assert_eq!(diagnostics.len(), 1, "{diagnostics:#?}");
    assert_eq!(diagnostics[0].rule_id, RULE_INDENT_TYPE);
}

#[test]
fn ignores_raw_string_indentation() {
    let diagnostics = analyze(
        Config::default(),
        "fn accepted() {\n    let text = r#\"\n\ttext, not indentation\n\"#;\n}\n",
    );

    assert!(diagnostics.is_empty(), "{diagnostics:#?}");
}

#[test]
fn reports_casing_diagnostics() {
    let mut config = Config::default();
    config.casing.enabled = true;
    config.casing.functions = CasingStyle::SnakeCase;
    config.casing.variables = CasingStyle::SnakeCase;
    config.casing.types = CasingStyle::UpperCamelCase;
    config.casing.constants = CasingStyle::SnakeUpperCase;

    let diagnostics = analyze(
        config,
        r#"const max_connections: usize = 1;

struct user_record;

fn Rejected(BadParam: i32) {
    let BadLocal = BadParam;
}
"#,
    );

    let rule_ids = diagnostics
        .iter()
        .map(|diagnostic| diagnostic.rule_id.as_str())
        .collect::<Vec<_>>();
    for expected in [
        RULE_CONSTANT_CASING,
        RULE_TYPE_CASING,
        RULE_FUNCTION_CASING,
        RULE_VARIABLE_CASING,
    ] {
        assert!(rule_ids.contains(&expected), "{diagnostics:#?}");
    }
}

#[test]
fn accepts_rust_language_default_casing() {
    let mut config = Config::default();
    config.casing.enabled = true;

    let diagnostics = analyze(
        config,
        r#"const MAX_CONNECTIONS: usize = 1;
static REQUEST_LIMIT: usize = 2;

struct UserRecord;
enum UserState {}

fn serve_http() {
    let request_id = 1;
}
"#,
    );

    assert!(diagnostics.is_empty(), "{diagnostics:#?}");
}

#[test]
fn honors_casing_ignores() {
    let mut config = Config::default();
    config.casing.enabled = true;
    config.casing.functions = CasingStyle::SnakeCase;
    config.casing.ignore_patterns = vec!["^Test[A-Z]".to_string()];

    let diagnostics = analyze(config, "fn TestAccepted() {}\n");

    assert!(diagnostics.is_empty(), "{diagnostics:#?}");
}

#[test]
fn reports_unpinned_github_actions() {
    let mut config = Config::default();
    config.github_actions_pinned.enabled = true;

    for (name, action) in [
        ("tag", "actions/checkout@v5"),
        ("branch", "actions/checkout@main"),
        ("missing-ref", "actions/checkout"),
        ("short-sha", "actions/checkout@f43a0e5ff2bd"),
        (
            "non-hex-40",
            "actions/checkout@zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
        ),
    ] {
        let diagnostics = analyze_workflow(
            config.clone(),
            &format!(
                r#"name: test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: {action}
"#
            ),
        );

        assert_eq!(diagnostics.len(), 1, "{name}: {diagnostics:#?}");
        assert_eq!(diagnostics[0].rule_id, RULE_GITHUB_ACTIONS_PINNED);
        assert_eq!(diagnostics[0].line, 6);
    }
}

#[test]
fn accepts_pinned_and_ignored_github_actions() {
    let mut config = Config::default();
    config.github_actions_pinned.enabled = true;

    for (name, source) in [
        (
            "full-sha",
            r#"name: test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
"#,
        ),
        (
            "full-sha-uppercase",
            r#"name: test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@F43A0E5FF2BD294095638E18286CA9A3D1956744
"#,
        ),
        (
            "nested-action-path",
            r#"name: test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: owner/repo/path/to/action@f43a0e5ff2bd294095638e18286ca9a3d1956744
"#,
        ),
        (
            "local-action",
            r#"name: test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build
"#,
        ),
        (
            "docker-action",
            r#"name: test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://alpine:3.19
"#,
        ),
        (
            "reusable-workflow",
            r#"name: test
jobs:
  call:
    uses: owner/repo/.github/workflows/build.yml@main
"#,
        ),
    ] {
        let diagnostics = analyze_workflow(config.clone(), source);

        assert!(diagnostics.is_empty(), "{name}: {diagnostics:#?}");
    }
}
