package cppanalysis

import (
	"errors"
	"fmt"
	"strings"
	"testing"

	"github.com/gdevillele/vet/implementations/cpp/internal/config"
)

type stubRunner struct {
	lookPath    string
	lookPathErr error
	// runs maps "name arg1 arg2 ..." to scripted results. When empty, Run
	// falls back to runOutput/runExitCode/runErr.
	runs        map[string]stubRun
	runOutput   []byte
	runExitCode int
	runErr      error
	lookCalls   []string
	runCalls    [][]string
}

type stubRun struct {
	output   []byte
	exitCode int
	err      error
}

func (s *stubRunner) LookPath(file string) (string, error) {
	s.lookCalls = append(s.lookCalls, file)
	if s.lookPathErr != nil {
		return "", s.lookPathErr
	}
	if s.lookPath != "" {
		return s.lookPath, nil
	}
	return file, nil
}

func (s *stubRunner) Run(name string, args []string) ([]byte, int, error) {
	s.runCalls = append(s.runCalls, append([]string{name}, args...))
	key := name + " " + strings.Join(args, " ")
	if s.runs != nil {
		if result, ok := s.runs[key]; ok {
			return result.output, result.exitCode, result.err
		}
	}
	return s.runOutput, s.runExitCode, s.runErr
}

func TestAnalyzeFileReportsMissingRequiredHeader(t *testing.T) {
	cfg := config.Default()
	cfg.SourceFileHeader.Required = true
	cfg.Format.Enabled = false

	diagnostics, err := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path:   "sample.c",
		Source: []byte("#include <stdio.h>\n"),
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}
	if diagnostics[0].RuleID != RuleSourceFileHeaderRequired {
		t.Fatalf("expected rule %q, got %q", RuleSourceFileHeaderRequired, diagnostics[0].RuleID)
	}
}

func TestAnalyzeFileReportsHeaderBelowMinimumLength(t *testing.T) {
	cfg := config.Default()
	cfg.SourceFileHeader.MinLength = 5
	cfg.Format.Enabled = false

	diagnostics, err := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path: "sample.c",
		Source: []byte(`// Tiny
int main(void) { return 0; }
`),
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}
	if diagnostics[0].RuleID != RuleSourceFileHeaderMin {
		t.Fatalf("expected rule %q, got %q", RuleSourceFileHeaderMin, diagnostics[0].RuleID)
	}
}

func TestAnalyzeFileReportsHeaderAboveMaximumLength(t *testing.T) {
	cfg := config.Default()
	cfg.SourceFileHeader.MaxLength = 5
	cfg.Format.Enabled = false

	diagnostics, err := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path: "sample.cpp",
		Source: []byte(`// Too long
int main() { return 0; }
`),
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}
	if diagnostics[0].RuleID != RuleSourceFileHeaderMax {
		t.Fatalf("expected rule %q, got %q", RuleSourceFileHeaderMax, diagnostics[0].RuleID)
	}
}

func TestAnalyzeFileAcceptsBlockCommentHeader(t *testing.T) {
	cfg := config.Default()
	cfg.SourceFileHeader.Required = true
	cfg.SourceFileHeader.MinLength = 10
	cfg.Format.Enabled = false

	diagnostics, err := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path: "sample.h",
		Source: []byte(`/*
 * Project header
 */
#pragma once
`),
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}

	if len(diagnostics) != 0 {
		t.Fatalf("expected no diagnostics, got %d: %#v", len(diagnostics), diagnostics)
	}
}

func TestAnalyzeFileDoesNotUseGeneratedMarkerAsHeader(t *testing.T) {
	cfg := config.Default()
	cfg.SourceFileHeader.Required = true
	cfg.Format.Enabled = false

	diagnostics, err := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path: "sample.c",
		Source: []byte(`// Code generated by test; DO NOT EDIT.
int value = 1;
`),
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}
	if diagnostics[0].RuleID != RuleSourceFileHeaderRequired {
		t.Fatalf("expected rule %q, got %q", RuleSourceFileHeaderRequired, diagnostics[0].RuleID)
	}
}

func TestAnalyzeFileReportsSourceFileAboveMaximumLines(t *testing.T) {
	cfg := config.Default()
	cfg.SourceFileLines.Max = 2
	cfg.Format.Enabled = false

	diagnostics, err := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path: "sample.c",
		Source: []byte(`int one = 1;
int two = 2;
int three = 3;
`),
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}
	if diagnostics[0].RuleID != RuleSourceFileLines {
		t.Fatalf("expected rule %q, got %q", RuleSourceFileLines, diagnostics[0].RuleID)
	}
}

func TestAnalyzeFileReportsUnformattedSource(t *testing.T) {
	cfg := config.Default()
	cfg.Format.Enabled = true
	runner := &stubRunner{
		lookPath:    "/usr/bin/clang-format",
		runExitCode: 1,
		runOutput:   []byte("sample.c:1:1: error: code should be clang-formatted [-Wclang-format-violations]\n"),
	}

	diagnostics, err := NewWithRunner(cfg, runner).AnalyzeFile(AnalyzeFileRequest{
		Path:   "sample.c",
		Source: []byte("int main(void){return 0;}\n"),
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}
	if diagnostics[0].RuleID != RuleSourceFormat {
		t.Fatalf("expected rule %q, got %q", RuleSourceFormat, diagnostics[0].RuleID)
	}
	if diagnostics[0].Message != "file is not clang-format-formatted" {
		t.Fatalf("unexpected message %q", diagnostics[0].Message)
	}
	if diagnostics[0].Line != 1 || diagnostics[0].Column != 1 {
		t.Fatalf("expected location 1:1, got %d:%d", diagnostics[0].Line, diagnostics[0].Column)
	}

	if len(runner.lookCalls) != 1 || runner.lookCalls[0] != "clang-format" {
		t.Fatalf("expected LookPath(clang-format), got %#v", runner.lookCalls)
	}
	if len(runner.runCalls) != 1 {
		t.Fatalf("expected one Run call, got %#v", runner.runCalls)
	}
	call := runner.runCalls[0]
	if len(call) != 4 || call[0] != "/usr/bin/clang-format" || call[1] != "--dry-run" || call[2] != "--Werror" || call[3] != "sample.c" {
		t.Fatalf("unexpected Run args: %#v", call)
	}
}

func TestAnalyzeFileAcceptsFormattedSource(t *testing.T) {
	cfg := config.Default()
	cfg.Format.Enabled = true
	runner := &stubRunner{
		lookPath:    "/usr/bin/clang-format",
		runExitCode: 0,
	}

	diagnostics, err := NewWithRunner(cfg, runner).AnalyzeFile(AnalyzeFileRequest{
		Path:   "sample.c",
		Source: []byte("int main(void) { return 0; }\n"),
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}
	if len(diagnostics) != 0 {
		t.Fatalf("expected no diagnostics, got %#v", diagnostics)
	}
}

func TestAnalyzeFileHonorsDisabledFormatCheck(t *testing.T) {
	cfg := config.Default()
	cfg.Format.Enabled = false
	runner := &stubRunner{
		lookPathErr: errors.New("should not be consulted"),
	}

	diagnostics, err := NewWithRunner(cfg, runner).AnalyzeFile(AnalyzeFileRequest{
		Path:   "sample.c",
		Source: []byte("int main(void){return 0;}\n"),
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}
	if len(diagnostics) != 0 {
		t.Fatalf("expected no diagnostics, got %#v", diagnostics)
	}
	if len(runner.lookCalls) != 0 {
		t.Fatalf("expected no LookPath when format disabled, got %#v", runner.lookCalls)
	}
}

func TestAnalyzeFileErrorsWhenClangFormatMissing(t *testing.T) {
	cfg := config.Default()
	cfg.Format.Enabled = true
	runner := &stubRunner{
		lookPathErr: errors.New("executable file not found in $PATH"),
	}

	diagnostics, err := NewWithRunner(cfg, runner).AnalyzeFile(AnalyzeFileRequest{
		Path:   "sample.c",
		Source: []byte("int main(void) { return 0; }\n"),
	})
	if err == nil {
		t.Fatalf("expected error when clang-format is missing")
	}
	if diagnostics != nil {
		t.Fatalf("expected nil diagnostics on tool error, got %#v", diagnostics)
	}
	if !strings.Contains(err.Error(), "clang-format not found in PATH") {
		t.Fatalf("expected missing-tool message, got %q", err.Error())
	}
	if !strings.Contains(err.Error(), "VET008") {
		t.Fatalf("expected VET008 mention in error, got %q", err.Error())
	}
}

func TestAnalyzeFileErrorsWhenClangFormatFailsToStart(t *testing.T) {
	cfg := config.Default()
	cfg.Format.Enabled = true
	runner := &stubRunner{
		lookPath: "/usr/bin/clang-format",
		runErr:   fmt.Errorf("permission denied"),
	}

	_, err := NewWithRunner(cfg, runner).AnalyzeFile(AnalyzeFileRequest{
		Path:   "sample.c",
		Source: []byte("int main(void) { return 0; }\n"),
	})
	if err == nil {
		t.Fatalf("expected error when clang-format fails to start")
	}
	if !strings.Contains(err.Error(), "run clang-format") {
		t.Fatalf("expected run error, got %q", err.Error())
	}
}

func TestAnalyzeFileAcceptsHeaderAfterUTF8BOM(t *testing.T) {
	cfg := config.Default()
	cfg.SourceFileHeader.Required = true
	cfg.SourceFileHeader.MinLength = 10
	cfg.Format.Enabled = false

	// UTF-8 BOM + sufficient header comment.
	source := append([]byte{0xEF, 0xBB, 0xBF}, []byte("// Project header\nint main(void) { return 0; }\n")...)
	diagnostics, err := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path:   "sample.c",
		Source: source,
	})
	if err != nil {
		t.Fatalf("AnalyzeFile returned error: %v", err)
	}

	if len(diagnostics) != 0 {
		t.Fatalf("expected no diagnostics with BOM + header, got %d: %#v", len(diagnostics), diagnostics)
	}
}

func TestAnalyzeWorkflowFileReportsUnpinnedAction(t *testing.T) {
	cfg := config.Default()
	cfg.GithubActionsPinned.Enabled = true

	diagnostics, err := New(cfg).AnalyzeWorkflowFile(AnalyzeWorkflowFileRequest{
		Path: "workflow.yml",
		Source: []byte(`name: sample
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
`),
	})
	if err != nil {
		t.Fatalf("AnalyzeWorkflowFile returned error: %v", err)
	}

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}
	if diagnostics[0].RuleID != RuleGithubActionsPinned {
		t.Fatalf("expected rule %q, got %q", RuleGithubActionsPinned, diagnostics[0].RuleID)
	}
}

func TestAnalyzeWorkflowFileAcceptsFullSHA(t *testing.T) {
	cfg := config.Default()
	cfg.GithubActionsPinned.Enabled = true

	diagnostics, err := New(cfg).AnalyzeWorkflowFile(AnalyzeWorkflowFileRequest{
		Path: "workflow.yml",
		Source: []byte(`name: sample
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
`),
	})
	if err != nil {
		t.Fatalf("AnalyzeWorkflowFile returned error: %v", err)
	}

	if len(diagnostics) != 0 {
		t.Fatalf("expected no diagnostics, got %d: %#v", len(diagnostics), diagnostics)
	}
}

