package cppanalysis

import (
	"strings"
	"testing"

	"github.com/gdevillele/vet/implementations/cpp/internal/config"
	"github.com/gdevillele/vet/implementations/cpp/internal/diagnostic"
)

func TestAnalyzeFileReportsMissingRequiredHeader(t *testing.T) {
	cfg := config.Default()
	cfg.SourceFileHeader.Required = true

	diagnostics := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path:   "sample.c",
		Source: []byte("#include <stdio.h>\n"),
	})

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}
	if diagnostics[0].RuleID != RuleSourceFileHeaderRequired {
		t.Fatalf("expected rule %q, got %q", RuleSourceFileHeaderRequired, diagnostics[0].RuleID)
	}
}

func TestAnalyzeFileReportsHeaderBelowMinimumLength(t *testing.T) {
	cfg := config.Default()
	cfg.SourceFileHeader.MinLength = 5

	diagnostics := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path: "sample.c",
		Source: []byte(`// Tiny
int main(void) { return 0; }
`),
	})

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}
	if diagnostics[0].RuleID != RuleSourceFileHeaderMin {
		t.Fatalf("expected rule %q, got %q", RuleSourceFileHeaderMin, diagnostics[0].RuleID)
	}
}

func TestAnalyzeFileReportsHeaderAboveMaximumLength(t *testing.T) {
	cfg := config.Default()
	cfg.SourceFileHeader.MaxLength = 5

	diagnostics := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path: "sample.cpp",
		Source: []byte(`// Too long
int main() { return 0; }
`),
	})

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}
	if diagnostics[0].RuleID != RuleSourceFileHeaderMax {
		t.Fatalf("expected rule %q, got %q", RuleSourceFileHeaderMax, diagnostics[0].RuleID)
	}
}

func TestAnalyzeFileAcceptsBlockCommentHeader(t *testing.T) {
	cfg := config.Default()
	cfg.SourceFileHeader.Required = true
	cfg.SourceFileHeader.MinLength = 10

	diagnostics := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path: "sample.h",
		Source: []byte(`/*
 * Project header
 */
#pragma once
`),
	})

	if len(diagnostics) != 0 {
		t.Fatalf("expected no diagnostics, got %d: %#v", len(diagnostics), diagnostics)
	}
}

func TestAnalyzeFileDoesNotUseGeneratedMarkerAsHeader(t *testing.T) {
	cfg := config.Default()
	cfg.SourceFileHeader.Required = true

	diagnostics := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path: "sample.c",
		Source: []byte(`// Code generated by test; DO NOT EDIT.
int value = 1;
`),
	})

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}
	if diagnostics[0].RuleID != RuleSourceFileHeaderRequired {
		t.Fatalf("expected rule %q, got %q", RuleSourceFileHeaderRequired, diagnostics[0].RuleID)
	}
}

func TestAnalyzeFileReportsSourceFileAboveMaximumLines(t *testing.T) {
	cfg := config.Default()
	cfg.SourceFileLines.Max = 2

	diagnostics := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path: "sample.c",
		Source: []byte(`int one = 1;
int two = 2;
int three = 3;
`),
	})

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}
	if diagnostics[0].RuleID != RuleSourceFileLines {
		t.Fatalf("expected rule %q, got %q", RuleSourceFileLines, diagnostics[0].RuleID)
	}
}

func TestAnalyzeFileReportsTabsWhenSpacesExpected(t *testing.T) {
	cfg := config.Default()
	cfg.Indent.Type = config.IndentSpaces

	diagnostics := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path: "sample.c",
		Source: []byte("int main(void) {\n\treturn 0;\n}\n"),
	})

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}
	if diagnostics[0].RuleID != RuleIndentType {
		t.Fatalf("expected rule %q, got %q", RuleIndentType, diagnostics[0].RuleID)
	}
	if diagnostics[0].Line != 2 {
		t.Fatalf("expected diagnostic on line 2, got %d", diagnostics[0].Line)
	}
}

func TestAnalyzeFileUsesSpacesAsLanguageDefault(t *testing.T) {
	cfg := config.Default()
	cfg.Indent.Type = config.IndentLanguageDefault

	diagnostics := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path: "sample.c",
		Source: []byte("int main(void) {\n\treturn 0;\n}\n"),
	})

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}
	if diagnostics[0].RuleID != RuleIndentType {
		t.Fatalf("expected rule %q, got %q", RuleIndentType, diagnostics[0].RuleID)
	}
}

func TestAnalyzeFileReportsIndentWidth(t *testing.T) {
	cfg := config.Default()
	cfg.Indent.Type = config.IndentSpaces
	cfg.Indent.Width = 4

	diagnostics := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path: "sample.c",
		Source: []byte("int main(void) {\n  return 0;\n}\n"),
	})

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}
	if diagnostics[0].RuleID != RuleIndentWidth {
		t.Fatalf("expected rule %q, got %q", RuleIndentWidth, diagnostics[0].RuleID)
	}
	if !strings.Contains(diagnostics[0].Message, "2 spaces") {
		t.Fatalf("expected width message, got %q", diagnostics[0].Message)
	}
}

func TestAnalyzeFileIgnoresIndentInsideBlockComments(t *testing.T) {
	cfg := config.Default()
	cfg.Indent.Type = config.IndentSpaces

	diagnostics := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path: "sample.c",
		Source: []byte("/*\n\tcomment with tab indent\n*/\nint main(void) { return 0; }\n"),
	})

	if len(diagnostics) != 0 {
		t.Fatalf("expected no diagnostics, got %d: %#v", len(diagnostics), diagnostics)
	}
}

func TestAnalyzeFileIgnoresIndentInsideRawString(t *testing.T) {
	cfg := config.Default()
	cfg.Indent.Type = config.IndentSpaces

	diagnostics := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path: "sample.cpp",
		Source: []byte("const char *text = R\"(\n\ttabbed raw string\n)\";\n"),
	})

	if len(diagnostics) != 0 {
		t.Fatalf("expected no diagnostics, got %d: %#v", len(diagnostics), diagnostics)
	}
}

func TestAnalyzeFileIgnoresIndentInsidePrefixedRawString(t *testing.T) {
	cfg := config.Default()
	cfg.Indent.Type = config.IndentSpaces

	for _, prefix := range []string{"u8", "L", "u", "U"} {
		source := "const char *text = " + prefix + "R\"(\n\ttabbed raw string\n)\";\n"
		diagnostics := New(cfg).AnalyzeFile(AnalyzeFileRequest{
			Path:   "sample.cpp",
			Source: []byte(source),
		})
		if len(diagnostics) != 0 {
			t.Fatalf("prefix %q: expected no diagnostics, got %d: %#v", prefix, len(diagnostics), diagnostics)
		}
	}
}

func TestAnalyzeFileMalformedRawStringDoesNotSuppressLaterIndent(t *testing.T) {
	cfg := config.Default()
	cfg.Indent.Type = config.IndentSpaces

	// Missing '(' after R" is not a valid raw string. The tab-indented line
	// that follows must still be checked (fail closed).
	source := []byte("const char *s = R\"hello\";\n\treturn 0;\n")
	diagnostics := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path:   "sample.cpp",
		Source: source,
	})

	if !hasRuleOnLine(diagnostics, RuleIndentType, 2) {
		t.Fatalf("expected VET008 on line 2 after malformed raw string, got %#v", diagnostics)
	}
}

func TestAnalyzeFileIdentifierAdjacentRDoesNotStartRawString(t *testing.T) {
	cfg := config.Default()
	cfg.Indent.Type = config.IndentSpaces

	// fooR" is not a raw-string token; later tab indent must still be reported.
	source := []byte("int fooR = 1;\nconst char *s = fooR\"(\n\tnot raw\n)\";\n\treturn 0;\n")
	diagnostics := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path:   "sample.cpp",
		Source: source,
	})

	if !hasRuleOnLine(diagnostics, RuleIndentType, 5) {
		t.Fatalf("expected VET008 on line 5 after identifier-adjacent R\", got %#v", diagnostics)
	}
}

func TestAnalyzeFileAcceptsHeaderAfterUTF8BOM(t *testing.T) {
	cfg := config.Default()
	cfg.SourceFileHeader.Required = true
	cfg.SourceFileHeader.MinLength = 10

	// UTF-8 BOM + sufficient header comment.
	source := append([]byte{0xEF, 0xBB, 0xBF}, []byte("// Project header\nint main(void) { return 0; }\n")...)
	diagnostics := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path:   "sample.c",
		Source: source,
	})

	if len(diagnostics) != 0 {
		t.Fatalf("expected no diagnostics with BOM + header, got %d: %#v", len(diagnostics), diagnostics)
	}
}

func TestAnalyzeFileIgnoresIndentOnSplicedLineComment(t *testing.T) {
	cfg := config.Default()
	cfg.Indent.Type = config.IndentSpaces

	// Physical line after // ...\ is still part of the comment (phase 2 splice).
	source := []byte("// continued comment\\\n\tstill comment\nint main(void) { return 0; }\n")
	diagnostics := New(cfg).AnalyzeFile(AnalyzeFileRequest{
		Path:   "sample.c",
		Source: source,
	})

	if len(diagnostics) != 0 {
		t.Fatalf("expected no indent diagnostics for spliced // comment, got %#v", diagnostics)
	}
}

func hasRuleOnLine(diagnostics []diagnostic.Diagnostic, ruleID string, line int) bool {
	for _, item := range diagnostics {
		if item.RuleID == ruleID && item.Line == line {
			return true
		}
	}
	return false
}

func TestAnalyzeWorkflowFileReportsUnpinnedAction(t *testing.T) {
	cfg := config.Default()
	cfg.GithubActionsPinned.Enabled = true

	diagnostics, err := New(cfg).AnalyzeWorkflowFile(AnalyzeWorkflowFileRequest{
		Path: "workflow.yml",
		Source: []byte(`name: sample
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
`),
	})
	if err != nil {
		t.Fatalf("AnalyzeWorkflowFile returned error: %v", err)
	}

	if len(diagnostics) != 1 {
		t.Fatalf("expected 1 diagnostic, got %d: %#v", len(diagnostics), diagnostics)
	}
	if diagnostics[0].RuleID != RuleGithubActionsPinned {
		t.Fatalf("expected rule %q, got %q", RuleGithubActionsPinned, diagnostics[0].RuleID)
	}
}

func TestAnalyzeWorkflowFileAcceptsFullSHA(t *testing.T) {
	cfg := config.Default()
	cfg.GithubActionsPinned.Enabled = true

	diagnostics, err := New(cfg).AnalyzeWorkflowFile(AnalyzeWorkflowFileRequest{
		Path: "workflow.yml",
		Source: []byte(`name: sample
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
`),
	})
	if err != nil {
		t.Fatalf("AnalyzeWorkflowFile returned error: %v", err)
	}

	if len(diagnostics) != 0 {
		t.Fatalf("expected no diagnostics, got %d: %#v", len(diagnostics), diagnostics)
	}
}
