import XCTest
@testable import VetCore

final class SwiftAnalyzerTests: XCTestCase {
    func testReportsFunctionsWithTooManyParameters() {
        let source = """
        func accepted(_ value: Int) {}

        func rejected(_ left: Int, _ right: Int) {}
        """

        let diagnostics = SwiftAnalyzer(config: .default()).analyzeFile(AnalyzeFileRequest(
            path: "sample.swift",
            source: source
        ))

        XCTAssertEqual(diagnostics.count, 1)
        XCTAssertEqual(diagnostics[0].ruleID, RuleID.maxFunctionParameters)
        XCTAssertEqual(diagnostics[0].line, 3)
        XCTAssertEqual(diagnostics[0].column, 6)
    }

    func testIgnoresCommasInsideNestedParameterTypes() {
        let source = """
        func accepted(_ handler: (Int, Int) -> Void) {}
        """

        let diagnostics = SwiftAnalyzer(config: .default()).analyzeFile(AnalyzeFileRequest(
            path: "sample.swift",
            source: source
        ))

        XCTAssertEqual(diagnostics.count, 0)
    }

    func testReportsMissingRequiredHeader() {
        var config = VetConfig.default()
        config.sourceFileHeader.required = true

        let diagnostics = SwiftAnalyzer(config: config).analyzeFile(AnalyzeFileRequest(
            path: "sample.swift",
            source: "func accepted(_ value: Int) {}\n"
        ))

        XCTAssertEqual(diagnostics.count, 1)
        XCTAssertEqual(diagnostics[0].ruleID, RuleID.sourceFileHeaderRequired)
    }

    func testReportsHeaderBelowMinimumLength() {
        var config = VetConfig.default()
        config.sourceFileHeader.minLength = 5

        let diagnostics = SwiftAnalyzer(config: config).analyzeFile(AnalyzeFileRequest(
            path: "sample.swift",
            source: """
            // Tiny
            func accepted(_ value: Int) {}
            """
        ))

        XCTAssertEqual(diagnostics.count, 1)
        XCTAssertEqual(diagnostics[0].ruleID, RuleID.sourceFileHeaderMin)
    }

    func testReportsHeaderAboveMaximumLength() {
        var config = VetConfig.default()
        config.sourceFileHeader.maxLength = 5

        let diagnostics = SwiftAnalyzer(config: config).analyzeFile(AnalyzeFileRequest(
            path: "sample.swift",
            source: """
            // Too long
            func accepted(_ value: Int) {}
            """
        ))

        XCTAssertEqual(diagnostics.count, 1)
        XCTAssertEqual(diagnostics[0].ruleID, RuleID.sourceFileHeaderMax)
    }

    func testSkipsSwiftToolsVersionWhenFindingHeader() {
        var config = VetConfig.default()
        config.sourceFileHeader.required = true
        config.sourceFileHeader.minLength = 10

        let diagnostics = SwiftAnalyzer(config: config).analyzeFile(AnalyzeFileRequest(
            path: "Package.swift",
            source: """
            // swift-tools-version: 6.0

            // Project header
            import PackageDescription
            """
        ))

        XCTAssertEqual(diagnostics.count, 0)
    }

    func testDoesNotUseGeneratedMarkerAsHeader() {
        var config = VetConfig.default()
        config.sourceFileHeader.required = true

        let diagnostics = SwiftAnalyzer(config: config).analyzeFile(AnalyzeFileRequest(
            path: "sample.swift",
            source: """
            // Code generated by test; DO NOT EDIT.
            func accepted(_ value: Int) {}
            """
        ))

        XCTAssertEqual(diagnostics.count, 1)
        XCTAssertEqual(diagnostics[0].ruleID, RuleID.sourceFileHeaderRequired)
    }

    func testReportsSourceFileAboveMaximumLines() {
        var config = VetConfig.default()
        config.sourceFileLines.max = 2

        let diagnostics = SwiftAnalyzer(config: config).analyzeFile(AnalyzeFileRequest(
            path: "sample.swift",
            source: """
            let one = 1
            let two = 2
            let three = 3
            """
        ))

        XCTAssertEqual(diagnostics.count, 1)
        XCTAssertEqual(diagnostics[0].ruleID, RuleID.sourceFileLines)
    }

    func testReportsFunctionBodyAboveMaximumLines() {
        var config = VetConfig.default()
        config.functionBodyLines.max = 1

        let diagnostics = SwiftAnalyzer(config: config).analyzeFile(AnalyzeFileRequest(
            path: "sample.swift",
            source: """
            func rejected() {
                print("one")
                print("two")
            }
            """
        ))

        XCTAssertEqual(diagnostics.count, 1)
        XCTAssertEqual(diagnostics[0].ruleID, RuleID.functionBodyLines)
    }

    func testReportsMissingMandatoryFunctionDocstring() {
        var config = VetConfig.default()
        config.functionDocstring.policy = .mandatory

        let diagnostics = SwiftAnalyzer(config: config).analyzeFile(AnalyzeFileRequest(
            path: "sample.swift",
            source: """
            func missing() {}

            /// documented has a docstring.
            func documented() {}
            """
        ))

        XCTAssertEqual(diagnostics.count, 1)
        XCTAssertEqual(diagnostics[0].ruleID, RuleID.functionDocstring)
    }

    func testReportsForbiddenFunctionDocstring() {
        var config = VetConfig.default()
        config.functionDocstring.policy = .forbidden

        let diagnostics = SwiftAnalyzer(config: config).analyzeFile(AnalyzeFileRequest(
            path: "sample.swift",
            source: """
            /// documented has a docstring.
            func documented() {}
            """
        ))

        XCTAssertEqual(diagnostics.count, 1)
        XCTAssertEqual(diagnostics[0].ruleID, RuleID.functionDocstring)
    }

    func testReportsTabsWhenSpacesIndentRequired() {
        var config = VetConfig.default()
        config.indent.type = .spaces

        let diagnostics = SwiftAnalyzer(config: config).analyzeFile(AnalyzeFileRequest(
            path: "sample.swift",
            source: "func rejected() {\n\tprint(\"one\")\n}\n"
        ))

        XCTAssertEqual(diagnostics.count, 1)
        XCTAssertEqual(diagnostics[0].ruleID, RuleID.indentType)
    }

    func testReportsSpacesWhenTabsIndentRequired() {
        var config = VetConfig.default()
        config.indent.type = .tabs

        let diagnostics = SwiftAnalyzer(config: config).analyzeFile(AnalyzeFileRequest(
            path: "sample.swift",
            source: "func rejected() {\n  print(\"one\")\n}\n"
        ))

        XCTAssertEqual(diagnostics.count, 1)
        XCTAssertEqual(diagnostics[0].ruleID, RuleID.indentType)
    }

    func testReportsIndentWidthViolation() {
        var config = VetConfig.default()
        config.indent.type = .spaces
        config.indent.width = 4

        let diagnostics = SwiftAnalyzer(config: config).analyzeFile(AnalyzeFileRequest(
            path: "sample.swift",
            source: "func rejected() {\n  print(\"one\")\n}\n"
        ))

        XCTAssertEqual(diagnostics.count, 1)
        XCTAssertEqual(diagnostics[0].ruleID, RuleID.indentWidth)
    }
}
