import XCTest
@testable import VetCore

final class SwiftAnalyzerTests: XCTestCase {
    func testReportsMissingRequiredHeader() throws {
        var config = VetConfig.default()
        config.format.enabled = false
        config.sourceFileHeader.required = true

        let diagnostics = try SwiftAnalyzer(config: config).analyzeFile(AnalyzeFileRequest(
            path: "sample.swift",
            source: "func accepted(_ value: Int) {}\n"
        ))

        XCTAssertEqual(diagnostics.count, 1)
        XCTAssertEqual(diagnostics[0].ruleID, RuleID.sourceFileHeaderRequired)
    }

    func testReportsHeaderBelowMinimumLength() throws {
        var config = VetConfig.default()
        config.format.enabled = false
        config.sourceFileHeader.minLength = 5

        let diagnostics = try SwiftAnalyzer(config: config).analyzeFile(AnalyzeFileRequest(
            path: "sample.swift",
            source: """
            // Tiny
            func accepted(_ value: Int) {}
            """
        ))

        XCTAssertEqual(diagnostics.count, 1)
        XCTAssertEqual(diagnostics[0].ruleID, RuleID.sourceFileHeaderMin)
    }

    func testReportsHeaderAboveMaximumLength() throws {
        var config = VetConfig.default()
        config.format.enabled = false
        config.sourceFileHeader.maxLength = 5

        let diagnostics = try SwiftAnalyzer(config: config).analyzeFile(AnalyzeFileRequest(
            path: "sample.swift",
            source: """
            // Too long
            func accepted(_ value: Int) {}
            """
        ))

        XCTAssertEqual(diagnostics.count, 1)
        XCTAssertEqual(diagnostics[0].ruleID, RuleID.sourceFileHeaderMax)
    }

    func testSkipsSwiftToolsVersionWhenFindingHeader() throws {
        var config = VetConfig.default()
        config.format.enabled = false
        config.sourceFileHeader.required = true
        config.sourceFileHeader.minLength = 10

        let diagnostics = try SwiftAnalyzer(config: config).analyzeFile(AnalyzeFileRequest(
            path: "Package.swift",
            source: """
            // swift-tools-version: 6.0

            // Project header
            import PackageDescription
            """
        ))

        XCTAssertEqual(diagnostics.count, 0)
    }

    func testDoesNotUseGeneratedMarkerAsHeader() throws {
        var config = VetConfig.default()
        config.format.enabled = false
        config.sourceFileHeader.required = true

        let diagnostics = try SwiftAnalyzer(config: config).analyzeFile(AnalyzeFileRequest(
            path: "sample.swift",
            source: """
            // Code generated by test; DO NOT EDIT.
            func accepted(_ value: Int) {}
            """
        ))

        XCTAssertEqual(diagnostics.count, 1)
        XCTAssertEqual(diagnostics[0].ruleID, RuleID.sourceFileHeaderRequired)
    }

    func testReportsSourceFileAboveMaximumLines() throws {
        var config = VetConfig.default()
        config.format.enabled = false
        config.sourceFileLines.max = 2

        let diagnostics = try SwiftAnalyzer(config: config).analyzeFile(AnalyzeFileRequest(
            path: "sample.swift",
            source: """
            let one = 1
            let two = 2
            let three = 3
            """
        ))

        XCTAssertEqual(diagnostics.count, 1)
        XCTAssertEqual(diagnostics[0].ruleID, RuleID.sourceFileLines)
    }

    func testDoesNotEnforceUnimplementedStructuralRules() throws {
        var config = VetConfig.default()
        config.format.enabled = false
        config.maxFunctionParameters.enabled = true
        config.maxFunctionParameters.max = 1
        config.functionBodyLines.max = 1
        config.functionDocstring.policy = .mandatory
        config.casing.enabled = true

        let diagnostics = try SwiftAnalyzer(config: config).analyzeFile(AnalyzeFileRequest(
            path: "sample.swift",
            source: """
            func rejected(_ left: Int, _ right: Int) {
                print("one")
                print("two")
            }
            """
        ))

        XCTAssertEqual(diagnostics, [])
    }

    func testReportsUnformattedSourceViaSwiftFormat() throws {
        var config = VetConfig.default()
        config.format.enabled = true

        // Extra space before `{` is rejected by swift-format Spacing rule.
        let diagnostics = try SwiftAnalyzer(config: config).analyzeFile(AnalyzeFileRequest(
            path: "sample.swift",
            source: "func rejected()  {\n  print(\"one\")\n}\n"
        ))

        XCTAssertEqual(diagnostics.count, 1)
        XCTAssertEqual(diagnostics[0].ruleID, RuleID.sourceFormat)
        XCTAssertEqual(diagnostics[0].message, "file is not swift-format-formatted")
        XCTAssertEqual(diagnostics[0].line, 1)
        XCTAssertEqual(diagnostics[0].column, 1)
    }

    func testHonorsDisabledFormatCheck() throws {
        var config = VetConfig.default()
        config.format.enabled = false

        let diagnostics = try SwiftAnalyzer(config: config).analyzeFile(AnalyzeFileRequest(
            path: "sample.swift",
            source: "func rejected()  {\n  print(\"one\")\n}\n"
        ))

        XCTAssertEqual(diagnostics.count, 0)
    }

    /// Regression: draining stdout/stderr only after waitUntilExit deadlocks when
    /// swift-format emits enough diagnostics to fill the OS pipe buffer (~64KB).
    func testLargeUnformattedSourceDoesNotDeadlockFormatCheck() throws {
        var config = VetConfig.default()
        config.format.enabled = true

        // Many Spacing-rule violations so swift-format produces large lint output.
        var lines: [String] = ["func large()  {"]
        for index in 0..<400 {
            lines.append("  print(  \(index)  )")
        }
        lines.append("}")
        let source = lines.joined(separator: "\n") + "\n"

        let diagnostics = try SwiftAnalyzer(config: config).analyzeFile(AnalyzeFileRequest(
            path: "large.swift",
            source: source
        ))

        XCTAssertEqual(diagnostics.count, 1)
        XCTAssertEqual(diagnostics[0].ruleID, RuleID.sourceFormat)
    }

    func testAcceptsSwiftFormatFormattedSource() throws {
        var config = VetConfig.default()
        config.format.enabled = true

        let diagnostics = try SwiftAnalyzer(config: config).analyzeFile(AnalyzeFileRequest(
            path: "sample.swift",
            source: "func accepted() {\n  print(\"one\")\n}\n"
        ))

        XCTAssertEqual(diagnostics, [])
    }

    func testReportsUnpinnedGitHubActions() throws {
        var config = VetConfig.default()
        config.githubActionsPinned.enabled = true

        for (name, action) in [
            ("tag", "actions/checkout@v5"),
            ("branch", "actions/checkout@main"),
            ("missing-ref", "actions/checkout"),
            ("short-sha", "actions/checkout@f43a0e5ff2bd"),
            ("non-hex-40", "actions/checkout@zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"),
        ] {
            let diagnostics = try GitHubActionsAnalyzer(config: config).analyzeFile(AnalyzeWorkflowFileRequest(
                path: "workflow.yml",
                source: """
                name: test
                jobs:
                  build:
                    runs-on: ubuntu-latest
                    steps:
                      - uses: \(action)
                """
            ))

            XCTAssertEqual(diagnostics.count, 1, name)
            XCTAssertEqual(diagnostics[0].ruleID, RuleID.githubActionsPinned, name)
            XCTAssertEqual(diagnostics[0].line, 6, name)
        }
    }

    func testAcceptsPinnedAndIgnoredGitHubActions() throws {
        var config = VetConfig.default()
        config.githubActionsPinned.enabled = true

        for (name, source) in [
            (
                "full-sha",
                """
                name: test
                jobs:
                  build:
                    runs-on: ubuntu-latest
                    steps:
                      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
                """
            ),
            (
                "full-sha-uppercase",
                """
                name: test
                jobs:
                  build:
                    runs-on: ubuntu-latest
                    steps:
                      - uses: actions/checkout@F43A0E5FF2BD294095638E18286CA9A3D1956744
                """
            ),
            (
                "nested-action-path",
                """
                name: test
                jobs:
                  build:
                    runs-on: ubuntu-latest
                    steps:
                      - uses: owner/repo/path/to/action@f43a0e5ff2bd294095638e18286ca9a3d1956744
                """
            ),
            (
                "local-action",
                """
                name: test
                jobs:
                  build:
                    runs-on: ubuntu-latest
                    steps:
                      - uses: ./.github/actions/build
                """
            ),
            (
                "docker-action",
                """
                name: test
                jobs:
                  build:
                    runs-on: ubuntu-latest
                    steps:
                      - uses: docker://alpine:3.19
                """
            ),
            (
                "reusable-workflow",
                """
                name: test
                jobs:
                  call:
                    uses: owner/repo/.github/workflows/build.yml@main
                """
            ),
        ] {
            let diagnostics = try GitHubActionsAnalyzer(config: config).analyzeFile(AnalyzeWorkflowFileRequest(
                path: "workflow.yml",
                source: source
            ))

            XCTAssertEqual(diagnostics.count, 0, name)
        }
    }
}
